import { colors, spacing, typography } from "@quasify-ui/tokens";
import { ETextType, TextStylePreset } from "./Text.props";

const DEFAULT_COLOR = colors.raisinBlack[800].value;
const LS_TIGHT = -0.02;

const BODY = typography.fontFamily.interRegular.value;
const BODY_MEDIUM = typography.fontFamily.interMedium.value;
const BODY_SEMIBOLD = typography.fontFamily.interSemiBold.value;
const BODY_BOLD = typography.fontFamily.interBold.value;
const DISPLAY = typography.fontFamily.jakartaBold.value;
const DISPLAY_SEMIBOLD = typography.fontFamily.jakartaSemiBold.value;
const DISPLAY_BLACK = typography.fontFamily.jakartaBlack.value;
const MONO = typography.fontFamily.jetbrainsMonoRegular.value;
const MONO_MEDIUM = typography.fontFamily.jetbrainsMonoMedium.value;

export const TEXT_PRESETS: Record<ETextType, TextStylePreset> = {
  [ETextType.button]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 15,
    fontWeight: "600",
    lineHeight: 21,
    letterSpacing: 0.01,
    color: colors.neutral[10].value,
    textAlign: "center",
  },
  [ETextType.label]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: spacing[14].value,
    fontWeight: "600",
    lineHeight: 20,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  // Display
  [ETextType.LDisplay]: {
    fontFamily: DISPLAY_BLACK,
    fontSize: 72,
    fontWeight: "800",
    lineHeight: 79,
    letterSpacing: -0.04,
    color: DEFAULT_COLOR,
  },
  [ETextType.MDisplay]: {
    fontFamily: DISPLAY_BLACK,
    fontSize: 60,
    fontWeight: "800",
    lineHeight: 66,
    letterSpacing: -0.03,
    color: DEFAULT_COLOR,
  },
  [ETextType.SDisplay]: {
    fontFamily: DISPLAY_BLACK,
    fontSize: 48,
    fontWeight: "800",
    lineHeight: 55,
    letterSpacing: -0.02,
    color: DEFAULT_COLOR,
  },
  // Labels
  [ETextType.XLLabel]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 28,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.LLabel]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 26,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.MLabel]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 24,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.SLabel]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 22,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XSLabel]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 16,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  // XXL Headings
  [ETextType.XXLHeadingBold]: {
    fontFamily: DISPLAY,
    fontSize: 40,
    fontWeight: "700",
    lineHeight: 48,
    letterSpacing: -0.03,
    color: DEFAULT_COLOR,
  },
  [ETextType.XXLHeadingSemiBold]: {
    fontFamily: DISPLAY_SEMIBOLD,
    fontSize: 40,
    fontWeight: "600",
    lineHeight: 48,
    letterSpacing: -0.03,
    color: DEFAULT_COLOR,
  },
  // XL Headings
  [ETextType.XLHeadingBold]: {
    fontFamily: DISPLAY,
    fontSize: 36,
    fontWeight: "700",
    lineHeight: 44,
    letterSpacing: -0.025,
    color: DEFAULT_COLOR,
  },
  [ETextType.XLHeadingSemiBold]: {
    fontFamily: DISPLAY_SEMIBOLD,
    fontSize: 36,
    fontWeight: "600",
    lineHeight: 44,
    letterSpacing: -0.025,
    color: DEFAULT_COLOR,
  },
  // L Headings
  [ETextType.LHeadingBold]: {
    fontFamily: DISPLAY,
    fontSize: 32,
    fontWeight: "700",
    lineHeight: 40,
    letterSpacing: -0.02,
    color: DEFAULT_COLOR,
  },
  [ETextType.LHeadingSemiBold]: {
    fontFamily: DISPLAY_SEMIBOLD,
    fontSize: 32,
    fontWeight: "600",
    lineHeight: 40,
    letterSpacing: -0.02,
    color: DEFAULT_COLOR,
  },
  // M Headings
  [ETextType.MHeadingBold]: {
    fontFamily: DISPLAY,
    fontSize: 28,
    fontWeight: "700",
    lineHeight: 36,
    letterSpacing: -0.015,
    color: DEFAULT_COLOR,
  },
  [ETextType.MHeadingSemiBold]: {
    fontFamily: DISPLAY_SEMIBOLD,
    fontSize: 28,
    fontWeight: "600",
    lineHeight: 36,
    letterSpacing: -0.015,
    color: DEFAULT_COLOR,
  },
  // S Headings
  [ETextType.SHeadingBold]: {
    fontFamily: DISPLAY,
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 32,
    letterSpacing: -0.01,
    color: DEFAULT_COLOR,
  },
  [ETextType.SHeadingSemiBold]: {
    fontFamily: DISPLAY_SEMIBOLD,
    fontSize: 24,
    fontWeight: "600",
    lineHeight: 32,
    letterSpacing: -0.01,
    color: DEFAULT_COLOR,
  },
  // XS Headings
  [ETextType.XSHeadingBold]: {
    fontFamily: DISPLAY,
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 28,
    letterSpacing: -0.01,
    color: DEFAULT_COLOR,
  },
  [ETextType.XSHeadingSemiBold]: {
    fontFamily: DISPLAY_SEMIBOLD,
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 28,
    letterSpacing: -0.01,
    color: DEFAULT_COLOR,
  },
  // XXS Headings
  [ETextType.XXSHeadingBold]: {
    fontFamily: DISPLAY,
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 26,
    letterSpacing: -0.005,
    color: DEFAULT_COLOR,
  },
  [ETextType.XXSHeadingSemiBold]: {
    fontFamily: DISPLAY_SEMIBOLD,
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 26,
    letterSpacing: -0.005,
    color: DEFAULT_COLOR,
  },
  // XXL Paragraphs
  [ETextType.XXLParagraphBold]: {
    fontFamily: BODY_BOLD,
    fontSize: 24,
    fontWeight: "700",
    lineHeight: 36,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XXLParagraphSemiBold]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 24,
    fontWeight: "600",
    lineHeight: 36,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XXLParagraphMedium]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 24,
    fontWeight: "500",
    lineHeight: 36,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XXLParagraphRegular]: {
    fontFamily: BODY,
    fontSize: 24,
    fontWeight: "400",
    lineHeight: 36,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  // XL Paragraphs
  [ETextType.XLParagraphBold]: {
    fontFamily: BODY_BOLD,
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 30,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XLParagraphSemiBold]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 30,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XLParagraphMedium]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 20,
    fontWeight: "500",
    lineHeight: 30,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XLParagraphRegular]: {
    fontFamily: BODY,
    fontSize: 20,
    fontWeight: "400",
    lineHeight: 30,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  // L Paragraphs
  [ETextType.LParagraphBold]: {
    fontFamily: BODY_BOLD,
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 28,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.LParagraphSemiBold]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 28,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.LParagraphMedium]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 18,
    fontWeight: "500",
    lineHeight: 28,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.LParagraphRegular]: {
    fontFamily: BODY,
    fontSize: 18,
    fontWeight: "400",
    lineHeight: 28,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  // M Paragraphs
  [ETextType.MParagraphBold]: {
    fontFamily: BODY_BOLD,
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 24,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.MParagraphSemiBold]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 24,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.MParagraphMedium]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 24,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.MParagraphRegular]: {
    fontFamily: BODY,
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 24,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  // S Paragraphs
  [ETextType.SParagraphBold]: {
    fontFamily: BODY_BOLD,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 22,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.SParagraphSemiBold]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 22,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.SParagraphMedium]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 22,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.SParagraphRegular]: {
    fontFamily: BODY,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 22,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  // XS Paragraphs
  [ETextType.XSParagraphBold]: {
    fontFamily: BODY_BOLD,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XSParagraphSemiBold]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XSParagraphMedium]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 18,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  [ETextType.XSParagraphRegular]: {
    fontFamily: BODY,
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 18,
    letterSpacing: LS_TIGHT,
    color: DEFAULT_COLOR,
  },
  // Portfolio roles
  [ETextType.Eyebrow]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 16,
    letterSpacing: 0.08,
    color: colors.celurenBlue[400].value,
  },
  [ETextType.HeroTitle]: {
    fontFamily: DISPLAY_BLACK,
    fontSize: 56,
    fontWeight: "800",
    lineHeight: 60,
    letterSpacing: -0.03,
    color: colors.neutral[10].value,
  },
  [ETextType.HeroSubtitle]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 20,
    fontWeight: "500",
    lineHeight: 30,
    letterSpacing: -0.01,
    color: DEFAULT_COLOR,
  },
  [ETextType.StatNumber]: {
    fontFamily: DISPLAY_BLACK,
    fontSize: 32,
    fontWeight: "800",
    lineHeight: 40,
    letterSpacing: -0.02,
    color: colors.neutral[10].value,
  },
  [ETextType.StatLabel]: {
    fontFamily: BODY,
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 20,
    color: colors.raisinBlack[200].value,
  },
  [ETextType.BadgeText]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 11,
    fontWeight: "500",
    lineHeight: 16,
    letterSpacing: 0.02,
    color: DEFAULT_COLOR,
  },
  [ETextType.CardTitle]: {
    fontFamily: DISPLAY_SEMIBOLD,
    fontSize: 17,
    fontWeight: "600",
    lineHeight: 24,
    letterSpacing: -0.01,
    color: colors.neutral[10].value,
  },
  [ETextType.CardDescription]: {
    fontFamily: BODY,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 22,
    color: colors.raisinBlack[100].value,
  },
  [ETextType.SectionHeading]: {
    fontFamily: DISPLAY_BLACK,
    fontSize: 36,
    fontWeight: "800",
    lineHeight: 44,
    letterSpacing: -0.025,
    color: colors.neutral[10].value,
  },
  [ETextType.OrganizationLabel]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 22,
    color: colors.celurenBlue[400].value,
  },
  [ETextType.LocationText]: {
    fontFamily: BODY,
    fontSize: 12,
    fontWeight: "400",
    lineHeight: 18,
    color: colors.raisinBlack[200].value,
  },
  [ETextType.HighlightText]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 20,
    color: colors.raisinBlack[100].value,
  },
  [ETextType.NavLabel]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    color: DEFAULT_COLOR,
  },
  [ETextType.FooterText]: {
    fontFamily: BODY,
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 20,
    color: colors.raisinBlack[200].value,
  },
  // Code / Mono
  [ETextType.CodeInline]: {
    fontFamily: MONO,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 21,
    color: DEFAULT_COLOR,
  },
  [ETextType.CodeBlock]: {
    fontFamily: MONO,
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 21,
    color: DEFAULT_COLOR,
  },
  [ETextType.CodeBlockLarge]: {
    fontFamily: MONO_MEDIUM,
    fontSize: 15,
    fontWeight: "500",
    lineHeight: 24,
    color: DEFAULT_COLOR,
  },
  // Aurora roles
  [ETextType.AuroraHeroTitle]: {
    fontFamily: DISPLAY_BLACK,
    fontSize: 72,
    fontWeight: "800",
    lineHeight: 77,
    letterSpacing: -0.03,
    color: colors.neutral[10].value,
  },
  [ETextType.AuroraHeroSubtitle]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 20,
    fontWeight: "500",
    lineHeight: 30,
    letterSpacing: -0.01,
    color: DEFAULT_COLOR,
  },
  [ETextType.AuroraStatNumber]: {
    fontFamily: DISPLAY_BLACK,
    fontSize: 36,
    fontWeight: "800",
    lineHeight: 45,
    letterSpacing: -0.02,
    color: colors.neutral[10].value,
  },
  [ETextType.AuroraStatLabel]: {
    fontFamily: BODY,
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 20,
    color: DEFAULT_COLOR,
  },
  [ETextType.AuroraNavLabel]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    color: DEFAULT_COLOR,
  },
  [ETextType.AuroraCardTitle]: {
    fontFamily: DISPLAY_SEMIBOLD,
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 26,
    letterSpacing: -0.01,
    color: colors.neutral[10].value,
  },
  [ETextType.AuroraCardDescription]: {
    fontFamily: BODY,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 22,
    color: DEFAULT_COLOR,
  },
  [ETextType.AuroraBadgeText]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 11,
    fontWeight: "500",
    lineHeight: 16,
    letterSpacing: 0.02,
    color: DEFAULT_COLOR,
  },
  [ETextType.AuroraToastMessage]: {
    fontFamily: BODY,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 22,
    color: DEFAULT_COLOR,
  },
  [ETextType.AuroraProgressLabel]: {
    fontFamily: BODY_MEDIUM,
    fontSize: 13,
    fontWeight: "500",
    lineHeight: 20,
    color: DEFAULT_COLOR,
  },
  [ETextType.AuroraDropZoneLabel]: {
    fontFamily: BODY_SEMIBOLD,
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 24,
    color: DEFAULT_COLOR,
  },
  [ETextType.AuroraDropZoneHint]: {
    fontFamily: BODY,
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 20,
    color: DEFAULT_COLOR,
  },
};
