import { type ComponentDef, type ThemeMode } from "./types";

export const THEMES: ThemeMode[] = ["quasar", "aurora", "steins-gate"];

export const ICONS: Record<string, string> = {
  Box: "▣",
  Stack: "▤",
  Grid: "⊞",
  Button: "▢",
  Input: "⌨",
  Checkbox: "☑",
  Switch: "⬡",
  Slider: "━",
  Table: "⊟",
  Progress: "▨",
  CircularProgress: "◎",
  Badge: "◉",
  Tag: "◈",
  NavBar: "≡",
  Tabs: "≣",
  Breadcrumb: "›",
  Pagination: "◀▶",
  Modal: "◻",
  Drawer: "▤",
  Tooltip: "◊",
  Dropdown: "▾",
  CommandPalette: "⌘",
  Avatar: "◒",
  Skeleton: "▭",
  Divider: "─",
  Card: "▢",
  Toast: "◐",
  Clipboard: "📋",
  Resizer: "⤡",
  ProgressPanel: "▦",
  FileDropZone: "📂",
  IconButton: "◎",
  HStack: "▤",
  VStack: "▥",
  Page: "◻",
};

export const COMPONENT_DEFS: ComponentDef[] = [
  { type: "Box", label: "Box", icon: "▣", category: "Layout", defaultProps: { p: 16, bg: "var(--color-surface)", borderRadius: 8 }, editableProps: ["bg"] },
  { type: "Stack", label: "Stack", icon: "▤", category: "Layout", defaultProps: { spacing: 8, direction: "vertical" }, editableProps: ["spacing", "direction"] },
  { type: "HStack", label: "HStack", icon: "▥", category: "Layout", defaultProps: { spacing: 8, direction: "horizontal" }, editableProps: ["spacing"] },
  { type: "Grid", label: "Grid", icon: "⊞", category: "Layout", defaultProps: { columns: 2, gap: 12 }, editableProps: ["columns", "gap"] },
  { type: "Button", label: "Button", icon: "▢", category: "Buttons", defaultProps: { type: "Primary", size: "MD" }, defaultChildren: "Click Me", editableProps: ["type", "size"] },
  { type: "IconButton", label: "IconButton", icon: "◎", category: "Buttons", defaultProps: { icon: "★", size: "MD" }, editableProps: ["icon", "size"] },
  { type: "Input", label: "Input", icon: "⌨", category: "Inputs", defaultProps: { placeholder: "Type here...", width: 240 }, editableProps: ["placeholder", "width"] },
  { type: "Checkbox", label: "Checkbox", icon: "☑", category: "Inputs", defaultProps: { label: "Option", checked: false }, editableProps: ["label", "checked"] },
  { type: "Switch", label: "Switch", icon: "⬡", category: "Inputs", defaultProps: { label: "Toggle", value: false }, editableProps: ["label", "value"] },
  { type: "Slider", label: "Slider", icon: "━", category: "Inputs", defaultProps: { min: 0, max: 100, value: 50, width: 200 }, editableProps: ["min", "max", "value", "width"] },
  { type: "FileDropZone", label: "FileDropZone", icon: "📂", category: "Inputs", defaultProps: { accept: "image/*", maxFiles: 5 }, editableProps: ["accept", "maxFiles"] },
  { type: "Table", label: "Table", icon: "⊟", category: "Data", defaultProps: { rows: 3, cols: 3 }, editableProps: ["rows", "cols"] },
  { type: "Progress", label: "Progress", icon: "▨", category: "Data", defaultProps: { value: 65, max: 100, width: 240 }, editableProps: ["value", "max", "width"] },
  { type: "CircularProgress", label: "CircularProgress", icon: "◎", category: "Data", defaultProps: { value: 75, size: 48 }, editableProps: ["value", "size"] },
  { type: "Badge", label: "Badge", icon: "◉", category: "Data", defaultProps: { label: "New", variant: "default" }, editableProps: ["label", "variant"] },
  { type: "Tag", label: "Tag", icon: "◈", category: "Data", defaultProps: { label: "stable", color: "#22c55e" }, editableProps: ["label", "color"] },
  { type: "NavBar", label: "NavBar", icon: "≡", category: "Navigation", defaultProps: { items: 3, brand: "App" }, editableProps: ["items", "brand"] },
  { type: "Tabs", label: "Tabs", icon: "≣", category: "Navigation", defaultProps: { tabs: 3, active: 0 }, editableProps: ["tabs", "active"] },
  { type: "Breadcrumb", label: "Breadcrumb", icon: "›", category: "Navigation", defaultProps: { items: 3 }, editableProps: ["items"] },
  { type: "Pagination", label: "Pagination", icon: "◀▶", category: "Navigation", defaultProps: { totalPages: 10, page: 1 }, editableProps: ["totalPages", "page"] },
  { type: "Modal", label: "Modal", icon: "◻", category: "Overlay", defaultProps: { title: "Modal Title" }, defaultChildren: "Modal content here", editableProps: ["title"] },
  { type: "Drawer", label: "Drawer", icon: "▤", category: "Overlay", defaultProps: { anchor: "right" }, editableProps: ["anchor"] },
  { type: "Tooltip", label: "Tooltip", icon: "◊", category: "Overlay", defaultProps: { content: "Tooltip text", placement: "top" }, editableProps: ["content", "placement"] },
  { type: "Dropdown", label: "Dropdown", icon: "▾", category: "Overlay", defaultProps: { items: 3, placeholder: "Select..." }, editableProps: ["items", "placeholder"] },
  { type: "CommandPalette", label: "CommandPalette", icon: "⌘", category: "Overlay", defaultProps: { placeholder: "Search commands..." }, editableProps: ["placeholder"] },
  { type: "Avatar", label: "Avatar", icon: "◒", category: "Media", defaultProps: { name: "SU", size: "md" }, editableProps: ["name", "size"] },
  { type: "Skeleton", label: "Skeleton", icon: "▭", category: "Media", defaultProps: { width: 240, height: 16 }, editableProps: ["width", "height"] },
  { type: "Divider", label: "Divider", icon: "─", category: "Media", defaultProps: { color: "var(--color-border)" }, editableProps: ["color"] },
  { type: "Card", label: "Card", icon: "▢", category: "Media", defaultProps: { p: 16, width: 280 }, editableProps: ["p", "width"] },
  { type: "Toast", label: "Toast", icon: "◐", category: "Feedback", defaultProps: { message: "Operation successful", variant: "success" }, editableProps: ["message", "variant"] },
  { type: "Clipboard", label: "Clipboard", icon: "📋", category: "Feedback", defaultProps: { value: "Copy me!" }, editableProps: ["value"] },
  { type: "Resizer", label: "Resizer", icon: "⤡", category: "Feedback", defaultProps: { defaultWidth: 400, minWidth: 200 }, editableProps: ["defaultWidth", "minWidth"] },
  { type: "ProgressPanel", label: "ProgressPanel", icon: "▦", category: "Feedback", defaultProps: { steps: 4, current: 2 }, editableProps: ["steps", "current"] },
];

export const CATEGORY_ICONS: Record<string, string> = {
  Layout: "◇",
  Buttons: "▤",
  Inputs: "⌨",
  Data: "⊟",
  Navigation: "≡",
  Overlay: "◻",
  Media: "◒",
  Feedback: "◐",
};

export const TOKENS_CATEGORIES: Record<string, Record<string, string>> = {
  Colors: {
    "Primary": "#ff6a1a", "Background": "#020205",
    "Surface": "rgba(255,255,255,0.04)", "Surface-2": "rgba(255,255,255,0.08)",
    "Text": "#f8f0e8", "Text-2": "rgba(248,240,232,0.6)",
    "Border": "rgba(255,106,26,0.15)", "Success": "#22c55e",
    "Error": "#dc143c", "Warning": "#f59e0b",
  },
  Spacing: {
    xs: "4px", sm: "8px", md: "16px", lg: "24px",
    xl: "32px", "2xl": "48px", "3xl": "64px", "4xl": "96px",
  },
  Typography: {
    H1: "2.5rem", H2: "2rem", H3: "1.5rem", H4: "1.25rem",
    Body: "1rem", Small: "0.875rem", XS: "0.75rem",
    "Weight-Bold": "700", "Weight-Medium": "500", "Weight-Regular": "400",
  },
  Radius: {
    none: "0", sm: "4px", md: "8px", lg: "12px",
    xl: "16px", "2xl": "24px", full: "9999px",
  },
  Shadow: {
    sm: "0 1px 2px rgba(0,0,0,0.3)",
    md: "0 4px 12px rgba(0,0,0,0.3)",
    lg: "0 8px 24px rgba(0,0,0,0.4)",
    xl: "0 12px 48px rgba(0,0,0,0.5)",
  },
};
