import { type ComponentDef, type ThemeMode, type PropMeta } from "./types";

export const THEMES: ThemeMode[] = ["quasar", "aurora", "steins-gate", "light"];

export const ICONS: Record<string, string> = {
  Box: "▣",
  Stack: "▤",
  Grid: "⊞",
  Button: "▢",
  Input: "⌨",
  Checkbox: "☑",
  Switch: "⬡",
  Slider: "━",
  Table: "⊟",
  Progress: "▨",
  CircularProgress: "◎",
  Badge: "◉",
  Tag: "◈",
  NavBar: "≡",
  Tabs: "≣",
  Breadcrumb: "›",
  Pagination: "◀▶",
  Modal: "◻",
  Drawer: "▤",
  Tooltip: "◊",
  Dropdown: "▾",
  CommandPalette: "⌘",
  Avatar: "◒",
  Skeleton: "▭",
  Divider: "─",
  Card: "▢",
  Toast: "◐",
  Clipboard: "📋",
  Resizer: "⤡",
  ProgressPanel: "▦",
  FileDropZone: "📂",
  IconButton: "◎",
  HStack: "▤",
  VStack: "▥",
  Page: "◻",
};

// ─── shared reusable meta blocks ────────────────────────────────────────────

const layoutMeta: PropMeta[] = [
  {
    key: "width",
    label: "Width",
    type: "number",
    min: 0,
    max: 2000,
    group: "Layout",
  },
  {
    key: "height",
    label: "Height",
    type: "number",
    min: 0,
    max: 2000,
    group: "Layout",
  },
  {
    key: "p",
    label: "Padding",
    type: "number",
    min: 0,
    max: 128,
    group: "Layout",
  },
  {
    key: "px",
    label: "Padding X",
    type: "number",
    min: 0,
    max: 128,
    group: "Layout",
  },
  {
    key: "py",
    label: "Padding Y",
    type: "number",
    min: 0,
    max: 128,
    group: "Layout",
  },
  {
    key: "m",
    label: "Margin",
    type: "number",
    min: 0,
    max: 128,
    group: "Layout",
  },
  {
    key: "gap",
    label: "Gap",
    type: "number",
    min: 0,
    max: 128,
    group: "Layout",
  },
  {
    key: "flex",
    label: "Flex",
    type: "number",
    min: 0,
    max: 10,
    group: "Layout",
  },
  {
    key: "minWidth",
    label: "Min Width",
    type: "number",
    min: 0,
    max: 2000,
    group: "Layout",
  },
  {
    key: "maxWidth",
    label: "Max Width",
    type: "number",
    min: 0,
    max: 2000,
    group: "Layout",
  },
  {
    key: "minHeight",
    label: "Min Height",
    type: "number",
    min: 0,
    max: 2000,
    group: "Layout",
  },
  {
    key: "maxHeight",
    label: "Max Height",
    type: "number",
    min: 0,
    max: 2000,
    group: "Layout",
  },
];

const appearanceMeta: PropMeta[] = [
  { key: "bg", label: "Background", type: "color", group: "Appearance" },
  { key: "color", label: "Color", type: "color", group: "Appearance" },
  {
    key: "borderColor",
    label: "Border Clr",
    type: "color",
    group: "Appearance",
  },
  {
    key: "opacity",
    label: "Opacity",
    type: "range",
    min: 0,
    max: 1,
    step: 0.05,
    group: "Appearance",
  },
  {
    key: "rounded",
    label: "Radius",
    type: "number",
    min: 0,
    max: 9999,
    group: "Appearance",
  },
  {
    key: "borderWidth",
    label: "Border W",
    type: "number",
    min: 0,
    max: 20,
    group: "Appearance",
  },
];

const flexMeta: PropMeta[] = [
  {
    key: "flexDirection",
    label: "Direction",
    type: "select",
    options: ["row", "column", "row-reverse", "column-reverse"],
    group: "Flex",
  },
  {
    key: "alignItems",
    label: "Align Items",
    type: "select",
    options: ["flex-start", "flex-end", "center", "stretch", "baseline"],
    group: "Flex",
  },
  {
    key: "justifyContent",
    label: "Justify",
    type: "select",
    options: [
      "flex-start",
      "flex-end",
      "center",
      "space-between",
      "space-around",
      "space-evenly",
    ],
    group: "Flex",
  },
  {
    key: "flexWrap",
    label: "Wrap",
    type: "select",
    options: ["nowrap", "wrap", "wrap-reverse"],
    group: "Flex",
  },
];

// ─── component definitions ──────────────────────────────────────────────────

export const COMPONENT_DEFS: ComponentDef[] = [
  // ── Layout ─────────────────────────────────────────────────────────────────
  {
    type: "Box",
    label: "Box",
    icon: "▣",
    category: "Layout",
    defaultProps: { p: 16, bg: "var(--color-surface)", borderRadius: 8 },
    editableProps: [
      "bg",
      "p",
      "px",
      "py",
      "m",
      "width",
      "height",
      "rounded",
      "borderWidth",
      "borderColor",
      "opacity",
      "flex",
      "flexDirection",
      "alignItems",
      "justifyContent",
      "flexWrap",
      "gap",
      "minWidth",
      "maxWidth",
      "minHeight",
      "maxHeight",
    ],
    propsMeta: [
      ...layoutMeta,
      ...appearanceMeta,
      ...flexMeta,
      {
        key: "scrollable",
        label: "Scrollable",
        type: "boolean",
        group: "Behaviour",
      },
      {
        key: "horizontal",
        label: "Horizontal",
        type: "boolean",
        group: "Behaviour",
      },
    ],
  },
  {
    type: "Stack",
    label: "Stack",
    icon: "▤",
    category: "Layout",
    defaultProps: { spacing: 8, direction: "vertical" },
    editableProps: [
      "spacing",
      "direction",
      "gap",
      "p",
      "bg",
      "width",
      "height",
      "alignItems",
      "justifyContent",
    ],
    propsMeta: [
      {
        key: "spacing",
        label: "Spacing",
        type: "number",
        min: 0,
        max: 128,
        group: "Layout",
      },
      ...layoutMeta,
      ...appearanceMeta,
      ...flexMeta,
    ],
  },
  {
    type: "HStack",
    label: "HStack",
    icon: "▥",
    category: "Layout",
    defaultProps: { spacing: 8 },
    editableProps: [
      "spacing",
      "gap",
      "p",
      "bg",
      "width",
      "height",
      "alignItems",
      "justifyContent",
      "flexWrap",
    ],
    propsMeta: [
      {
        key: "spacing",
        label: "Spacing",
        type: "number",
        min: 0,
        max: 128,
        group: "Layout",
      },
      ...layoutMeta,
      ...appearanceMeta,
      ...flexMeta,
    ],
  },
  {
    type: "VStack",
    label: "VStack",
    icon: "▥",
    category: "Layout",
    defaultProps: { spacing: 8 },
    editableProps: [
      "spacing",
      "gap",
      "p",
      "bg",
      "width",
      "height",
      "alignItems",
      "justifyContent",
    ],
    propsMeta: [
      {
        key: "spacing",
        label: "Spacing",
        type: "number",
        min: 0,
        max: 128,
        group: "Layout",
      },
      ...layoutMeta,
      ...appearanceMeta,
      ...flexMeta,
    ],
  },
  {
    type: "Grid",
    label: "Grid",
    icon: "⊞",
    category: "Layout",
    defaultProps: { columns: 2, gap: 12 },
    editableProps: ["columns", "gap", "p", "bg", "width", "height"],
    propsMeta: [
      {
        key: "columns",
        label: "Columns",
        type: "number",
        min: 1,
        max: 12,
        group: "Layout",
      },
      {
        key: "gap",
        label: "Gap",
        type: "number",
        min: 0,
        max: 128,
        group: "Layout",
      },
      ...layoutMeta.filter((m) => !["gap"].includes(m.key)),
      ...appearanceMeta,
    ],
  },

  // ── Buttons ─────────────────────────────────────────────────────────────────
  {
    type: "Button",
    label: "Button",
    icon: "▢",
    category: "Buttons",
    defaultProps: { type: "Primary", size: "MD" },
    defaultChildren: "Click Me",
    editableProps: ["type", "size", "loading", "disabled", "fullWidth"],
    propsMeta: [
      {
        key: "type",
        label: "Variant",
        type: "select",
        options: [
          "Primary",
          "Secondary",
          "Tertiary",
          "ghost",
          "outline",
          "danger",
          "link",
          "transparent",
          "with-border",
        ],
        group: "Appearance",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["SM", "MD", "LG", "XL", "XXL"],
        group: "Appearance",
      },
      { key: "loading", label: "Loading", type: "boolean", group: "State" },
      { key: "disabled", label: "Disabled", type: "boolean", group: "State" },
      {
        key: "fullWidth",
        label: "Full Width",
        type: "boolean",
        group: "Layout",
      },
      ...layoutMeta.filter((m) => ["width", "p", "m"].includes(m.key)),
    ],
  },
  {
    type: "IconButton",
    label: "IconButton",
    icon: "◎",
    category: "Buttons",
    defaultProps: { icon: "★", size: "MD" },
    editableProps: ["icon", "size", "disabled"],
    propsMeta: [
      {
        key: "icon",
        label: "Icon Char",
        type: "text",
        placeholder: "★",
        group: "Content",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["SM", "MD", "LG", "XL", "XXL"],
        group: "Appearance",
      },
      { key: "disabled", label: "Disabled", type: "boolean", group: "State" },
    ],
  },

  // ── Inputs ──────────────────────────────────────────────────────────────────
  {
    type: "Input",
    label: "Input",
    icon: "⌨",
    category: "Inputs",
    defaultProps: {
      placeholder: "Type here...",
      width: 240,
      type: "TextField",
      size: "Md",
    },
    editableProps: [
      "placeholder",
      "type",
      "size",
      "label",
      "hintText",
      "errorMessage",
      "isDisabled",
      "isRequired",
      "maxLength",
      "secureTextEntry",
      "multiline",
      "numberOfLines",
    ],
    propsMeta: [
      {
        key: "placeholder",
        label: "Placeholder",
        type: "text",
        group: "Content",
      },
      { key: "label", label: "Label", type: "text", group: "Content" },
      { key: "hintText", label: "Hint Text", type: "text", group: "Content" },
      {
        key: "errorMessage",
        label: "Error Msg",
        type: "text",
        group: "Content",
      },
      {
        key: "type",
        label: "Input Type",
        type: "select",
        options: [
          "TextField",
          "TextArea",
          "SearchBar",
          "PhoneNumber",
          "Number",
          "MoneyAmount",
          "Percentage",
        ],
        group: "Appearance",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["sm", "Md", "Lg"],
        group: "Appearance",
      },
      {
        key: "maxLength",
        label: "Max Length",
        type: "number",
        min: 0,
        max: 10000,
        group: "Behaviour",
      },
      { key: "isDisabled", label: "Disabled", type: "boolean", group: "State" },
      { key: "isRequired", label: "Required", type: "boolean", group: "State" },
      {
        key: "secureTextEntry",
        label: "Password",
        type: "boolean",
        group: "State",
      },
      { key: "multiline", label: "Multiline", type: "boolean", group: "State" },
      {
        key: "numberOfLines",
        label: "Lines",
        type: "number",
        min: 1,
        max: 20,
        group: "State",
      },
      {
        key: "autoFocus",
        label: "Auto Focus",
        type: "boolean",
        group: "State",
      },
      ...layoutMeta.filter((m) => ["width", "p"].includes(m.key)),
    ],
  },
  {
    type: "Checkbox",
    label: "Checkbox",
    icon: "☑",
    category: "Inputs",
    defaultProps: { label: "Option", checked: false, size: "md" },
    editableProps: [
      "label",
      "checked",
      "indeterminate",
      "disabled",
      "size",
      "color",
      "labelPosition",
    ],
    propsMeta: [
      { key: "label", label: "Label", type: "text", group: "Content" },
      { key: "checked", label: "Checked", type: "boolean", group: "State" },
      {
        key: "indeterminate",
        label: "Indeterminate",
        type: "boolean",
        group: "State",
      },
      { key: "disabled", label: "Disabled", type: "boolean", group: "State" },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["sm", "md", "lg"],
        group: "Appearance",
      },
      {
        key: "color",
        label: "Accent Color",
        type: "color",
        group: "Appearance",
      },
      {
        key: "labelPosition",
        label: "Label Side",
        type: "select",
        options: ["left", "right"],
        group: "Appearance",
      },
    ],
  },
  {
    type: "Switch",
    label: "Switch",
    icon: "⬡",
    category: "Inputs",
    defaultProps: { label: "Toggle", value: false, size: "md" },
    editableProps: [
      "label",
      "value",
      "disabled",
      "size",
      "activeColor",
      "inactiveColor",
      "labelPosition",
    ],
    propsMeta: [
      { key: "label", label: "Label", type: "text", group: "Content" },
      { key: "value", label: "On", type: "boolean", group: "State" },
      { key: "disabled", label: "Disabled", type: "boolean", group: "State" },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["sm", "md", "lg"],
        group: "Appearance",
      },
      {
        key: "activeColor",
        label: "Active Color",
        type: "color",
        group: "Appearance",
      },
      {
        key: "inactiveColor",
        label: "Inactive Color",
        type: "color",
        group: "Appearance",
      },
      {
        key: "labelPosition",
        label: "Label Side",
        type: "select",
        options: ["left", "right"],
        group: "Appearance",
      },
    ],
  },
  {
    type: "Slider",
    label: "Slider",
    icon: "━",
    category: "Inputs",
    defaultProps: { min: 0, max: 100, value: 50, width: 200, size: "md" },
    editableProps: [
      "min",
      "max",
      "value",
      "step",
      "size",
      "color",
      "trackColor",
      "disabled",
      "showValue",
    ],
    propsMeta: [
      {
        key: "value",
        label: "Value",
        type: "range",
        min: 0,
        max: 100,
        step: 1,
        group: "Content",
      },
      {
        key: "min",
        label: "Min",
        type: "number",
        min: -1000,
        max: 1000,
        group: "Content",
      },
      {
        key: "max",
        label: "Max",
        type: "number",
        min: -1000,
        max: 1000,
        group: "Content",
      },
      {
        key: "step",
        label: "Step",
        type: "number",
        min: 0,
        max: 100,
        group: "Content",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["sm", "md", "lg"],
        group: "Appearance",
      },
      {
        key: "color",
        label: "Track Color",
        type: "color",
        group: "Appearance",
      },
      {
        key: "trackColor",
        label: "BG Track",
        type: "color",
        group: "Appearance",
      },
      { key: "disabled", label: "Disabled", type: "boolean", group: "State" },
      {
        key: "showValue",
        label: "Show Value",
        type: "boolean",
        group: "State",
      },
      ...layoutMeta.filter((m) => ["width"].includes(m.key)),
    ],
  },
  {
    type: "FileDropZone",
    label: "FileDropZone",
    icon: "📂",
    category: "Inputs",
    defaultProps: { accept: "image/*", multiple: false },
    editableProps: ["accept", "multiple", "label", "hint"],
    propsMeta: [
      {
        key: "label",
        label: "Label",
        type: "text",
        placeholder: "Drop files here",
        group: "Content",
      },
      {
        key: "hint",
        label: "Hint",
        type: "text",
        placeholder: "PNG, JPG up to 5MB",
        group: "Content",
      },
      {
        key: "accept",
        label: "Accept",
        type: "text",
        placeholder: "image/*",
        group: "Behaviour",
      },
      {
        key: "multiple",
        label: "Multiple",
        type: "boolean",
        group: "Behaviour",
      },
    ],
  },

  // ── Data ────────────────────────────────────────────────────────────────────
  {
    type: "Table",
    label: "Table",
    icon: "⊟",
    category: "Data",
    defaultProps: { rows: 3, cols: 3 },
    editableProps: ["rows", "cols", "caption"],
    propsMeta: [
      {
        key: "rows",
        label: "Rows",
        type: "number",
        min: 1,
        max: 50,
        group: "Content",
      },
      {
        key: "cols",
        label: "Columns",
        type: "number",
        min: 1,
        max: 12,
        group: "Content",
      },
      {
        key: "caption",
        label: "Caption",
        type: "text",
        placeholder: "Table title",
        group: "Content",
      },
      ...layoutMeta.filter((m) => ["width"].includes(m.key)),
    ],
  },
  {
    type: "Progress",
    label: "Progress",
    icon: "▨",
    category: "Data",
    defaultProps: {
      value: 65,
      max: 100,
      width: 240,
      size: "md",
      variant: "default",
    },
    editableProps: [
      "value",
      "max",
      "size",
      "variant",
      "color",
      "trackColor",
      "label",
      "showLabel",
      "showPercentage",
      "animated",
    ],
    propsMeta: [
      {
        key: "value",
        label: "Value",
        type: "range",
        min: 0,
        max: 100,
        step: 1,
        group: "Content",
      },
      {
        key: "max",
        label: "Max",
        type: "number",
        min: 1,
        max: 1000,
        group: "Content",
      },
      {
        key: "label",
        label: "Label",
        type: "text",
        placeholder: "Loading...",
        group: "Content",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["xs", "sm", "md", "lg"],
        group: "Appearance",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: ["default", "gradient", "striped"],
        group: "Appearance",
      },
      { key: "color", label: "Bar Color", type: "color", group: "Appearance" },
      {
        key: "trackColor",
        label: "Track Color",
        type: "color",
        group: "Appearance",
      },
      {
        key: "showLabel",
        label: "Show Label",
        type: "boolean",
        group: "State",
      },
      {
        key: "showPercentage",
        label: "Show %",
        type: "boolean",
        group: "State",
      },
      { key: "animated", label: "Animated", type: "boolean", group: "State" },
      ...layoutMeta.filter((m) => ["width"].includes(m.key)),
    ],
  },
  {
    type: "CircularProgress",
    label: "CircularProgress",
    icon: "◎",
    category: "Data",
    defaultProps: { value: 75, size: "md" },
    editableProps: [
      "value",
      "max",
      "size",
      "thickness",
      "color",
      "trackColor",
      "showValue",
      "label",
      "animated",
    ],
    propsMeta: [
      {
        key: "value",
        label: "Value",
        type: "range",
        min: 0,
        max: 100,
        step: 1,
        group: "Content",
      },
      {
        key: "max",
        label: "Max",
        type: "number",
        min: 1,
        max: 1000,
        group: "Content",
      },
      {
        key: "label",
        label: "Label",
        type: "text",
        placeholder: "Done",
        group: "Content",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["xs", "sm", "md", "lg", "xl"],
        group: "Appearance",
      },
      {
        key: "thickness",
        label: "Thickness",
        type: "number",
        min: 1,
        max: 30,
        group: "Appearance",
      },
      { key: "color", label: "Bar Color", type: "color", group: "Appearance" },
      {
        key: "trackColor",
        label: "Track Color",
        type: "color",
        group: "Appearance",
      },
      {
        key: "showValue",
        label: "Show Value",
        type: "boolean",
        group: "State",
      },
      { key: "animated", label: "Animated", type: "boolean", group: "State" },
    ],
  },
  {
    type: "Badge",
    label: "Badge",
    icon: "◉",
    category: "Data",
    defaultProps: { label: "New", variant: "default" },
    editableProps: ["label", "variant"],
    propsMeta: [
      {
        key: "label",
        label: "Label",
        type: "text",
        placeholder: "New",
        group: "Content",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: ["default", "green", "amber", "red", "purple"],
        group: "Appearance",
      },
    ],
  },
  {
    type: "Tag",
    label: "Tag",
    icon: "◈",
    category: "Data",
    defaultProps: { label: "stable", color: "#22c55e", variant: "solid" },
    editableProps: ["label", "variant", "color"],
    propsMeta: [
      {
        key: "label",
        label: "Label",
        type: "text",
        placeholder: "stable",
        group: "Content",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: ["solid", "outline", "subtle"],
        group: "Appearance",
      },
      {
        key: "color",
        label: "Accent Color",
        type: "color",
        group: "Appearance",
      },
    ],
  },

  // ── Navigation ──────────────────────────────────────────────────────────────
  {
    type: "NavBar",
    label: "NavBar",
    icon: "≡",
    category: "Navigation",
    defaultProps: { items: 3, brand: "App", scrolled: false },
    editableProps: ["brand", "items", "scrolled"],
    propsMeta: [
      {
        key: "brand",
        label: "Brand",
        type: "text",
        placeholder: "App",
        group: "Content",
      },
      {
        key: "items",
        label: "# Links",
        type: "number",
        min: 0,
        max: 10,
        group: "Content",
      },
      { key: "scrolled", label: "Scrolled", type: "boolean", group: "State" },
    ],
  },
  {
    type: "Tabs",
    label: "Tabs",
    icon: "≣",
    category: "Navigation",
    defaultProps: {
      tabs: 3,
      active: 0,
      variant: "underline",
      fullWidth: false,
    },
    editableProps: ["tabs", "active", "variant", "fullWidth"],
    propsMeta: [
      {
        key: "tabs",
        label: "# Tabs",
        type: "number",
        min: 1,
        max: 10,
        group: "Content",
      },
      {
        key: "active",
        label: "Active",
        type: "number",
        min: 0,
        max: 9,
        group: "Content",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: ["underline", "pills", "card"],
        group: "Appearance",
      },
      {
        key: "fullWidth",
        label: "Full Width",
        type: "boolean",
        group: "Appearance",
      },
    ],
  },
  {
    type: "Breadcrumb",
    label: "Breadcrumb",
    icon: "›",
    category: "Navigation",
    defaultProps: { items: 3 },
    editableProps: ["items"],
    propsMeta: [
      {
        key: "items",
        label: "# Items",
        type: "number",
        min: 1,
        max: 10,
        group: "Content",
      },
    ],
  },
  {
    type: "Pagination",
    label: "Pagination",
    icon: "◀▶",
    category: "Navigation",
    defaultProps: {
      totalPages: 10,
      page: 1,
      showPrevNext: true,
      siblingCount: 7,
    },
    editableProps: ["totalPages", "page", "showPrevNext", "siblingCount"],
    propsMeta: [
      {
        key: "page",
        label: "Current Page",
        type: "number",
        min: 1,
        max: 1000,
        group: "Content",
      },
      {
        key: "totalPages",
        label: "Total Pages",
        type: "number",
        min: 1,
        max: 1000,
        group: "Content",
      },
      {
        key: "siblingCount",
        label: "Visible Pages",
        type: "number",
        min: 1,
        max: 15,
        group: "Content",
      },
      {
        key: "showPrevNext",
        label: "Prev/Next Btns",
        type: "boolean",
        group: "Appearance",
      },
    ],
  },

  // ── Overlay ─────────────────────────────────────────────────────────────────
  {
    type: "Modal",
    label: "Modal",
    icon: "◻",
    category: "Overlay",
    defaultProps: {
      title: "Modal Title",
      size: "md",
      closeOnBackdrop: true,
      showCloseButton: true,
    },
    defaultChildren: "Modal content here",
    editableProps: ["title", "size", "closeOnBackdrop", "showCloseButton"],
    propsMeta: [
      {
        key: "title",
        label: "Title",
        type: "text",
        placeholder: "Modal Title",
        group: "Content",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["xs", "sm", "md", "lg", "xl", "full"],
        group: "Appearance",
      },
      {
        key: "closeOnBackdrop",
        label: "Close on Backdrop",
        type: "boolean",
        group: "Behaviour",
      },
      {
        key: "showCloseButton",
        label: "Show Close Btn",
        type: "boolean",
        group: "Behaviour",
      },
    ],
  },
  {
    type: "Drawer",
    label: "Drawer",
    icon: "▤",
    category: "Overlay",
    defaultProps: { anchor: "right", title: "Drawer" },
    editableProps: ["anchor", "title"],
    propsMeta: [
      {
        key: "title",
        label: "Title",
        type: "text",
        placeholder: "Drawer",
        group: "Content",
      },
      {
        key: "anchor",
        label: "Side",
        type: "select",
        options: ["left", "right", "bottom"],
        group: "Appearance",
      },
    ],
  },
  {
    type: "Tooltip",
    label: "Tooltip",
    icon: "◊",
    category: "Overlay",
    defaultProps: { content: "Tooltip text", placement: "top" },
    editableProps: ["content", "placement"],
    propsMeta: [
      {
        key: "content",
        label: "Content",
        type: "text",
        placeholder: "Tooltip text",
        group: "Content",
      },
      {
        key: "placement",
        label: "Placement",
        type: "select",
        options: ["top", "bottom", "left", "right"],
        group: "Appearance",
      },
    ],
  },
  {
    type: "Dropdown",
    label: "Dropdown",
    icon: "▾",
    category: "Overlay",
    defaultProps: {
      items: 3,
      placeholder: "Select...",
      size: "md",
      searchable: false,
      multiple: false,
      disabled: false,
    },
    editableProps: [
      "items",
      "placeholder",
      "size",
      "searchable",
      "multiple",
      "disabled",
      "label",
      "errorMessage",
    ],
    propsMeta: [
      {
        key: "placeholder",
        label: "Placeholder",
        type: "text",
        placeholder: "Select...",
        group: "Content",
      },
      {
        key: "label",
        label: "Label",
        type: "text",
        placeholder: "Field label",
        group: "Content",
      },
      {
        key: "errorMessage",
        label: "Error Msg",
        type: "text",
        placeholder: "Error text",
        group: "Content",
      },
      {
        key: "items",
        label: "# Options",
        type: "number",
        min: 1,
        max: 20,
        group: "Content",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["sm", "md", "lg"],
        group: "Appearance",
      },
      {
        key: "searchable",
        label: "Searchable",
        type: "boolean",
        group: "Behaviour",
      },
      {
        key: "multiple",
        label: "Multi-select",
        type: "boolean",
        group: "Behaviour",
      },
      { key: "disabled", label: "Disabled", type: "boolean", group: "State" },
    ],
  },
  {
    type: "CommandPalette",
    label: "CommandPalette",
    icon: "⌘",
    category: "Overlay",
    defaultProps: { placeholder: "Search commands...", items: 4 },
    editableProps: ["placeholder", "items"],
    propsMeta: [
      {
        key: "placeholder",
        label: "Placeholder",
        type: "text",
        placeholder: "Search commands...",
        group: "Content",
      },
      {
        key: "items",
        label: "# Commands",
        type: "number",
        min: 1,
        max: 20,
        group: "Content",
      },
    ],
  },

  // ── Media ───────────────────────────────────────────────────────────────────
  {
    type: "Avatar",
    label: "Avatar",
    icon: "◒",
    category: "Media",
    defaultProps: { name: "SU", size: "md", shape: "circle" },
    editableProps: ["name", "src", "size", "shape", "status"],
    propsMeta: [
      {
        key: "name",
        label: "Name / Initials",
        type: "text",
        placeholder: "SU",
        group: "Content",
      },
      {
        key: "src",
        label: "Image URL",
        type: "text",
        placeholder: "https://...",
        group: "Content",
      },
      {
        key: "alt",
        label: "Alt Text",
        type: "text",
        placeholder: "User avatar",
        group: "Content",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["xs", "sm", "md", "lg", "xl", "2xl"],
        group: "Appearance",
      },
      {
        key: "shape",
        label: "Shape",
        type: "select",
        options: ["circle", "rounded", "square"],
        group: "Appearance",
      },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: ["", "online", "offline", "away", "busy"],
        group: "State",
      },
    ],
  },
  {
    type: "Skeleton",
    label: "Skeleton",
    icon: "▭",
    category: "Media",
    defaultProps: {
      width: 240,
      height: 16,
      variant: "rectangular",
      animated: true,
    },
    editableProps: [
      "width",
      "height",
      "variant",
      "lines",
      "animated",
      "baseColor",
      "highlightColor",
    ],
    propsMeta: [
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 10,
        max: 2000,
        group: "Layout",
      },
      {
        key: "height",
        label: "Height",
        type: "number",
        min: 4,
        max: 2000,
        group: "Layout",
      },
      {
        key: "lines",
        label: "Lines",
        type: "number",
        min: 1,
        max: 20,
        group: "Content",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: ["text", "circular", "rectangular", "rounded"],
        group: "Appearance",
      },
      {
        key: "baseColor",
        label: "Base Color",
        type: "color",
        group: "Appearance",
      },
      {
        key: "highlightColor",
        label: "Highlight Color",
        type: "color",
        group: "Appearance",
      },
      { key: "animated", label: "Animated", type: "boolean", group: "State" },
    ],
  },
  {
    type: "Divider",
    label: "Divider",
    icon: "─",
    category: "Media",
    defaultProps: {
      color: "var(--color-border)",
      orientation: "horizontal",
      variant: "solid",
      thickness: 1,
    },
    editableProps: [
      "orientation",
      "variant",
      "color",
      "thickness",
      "label",
      "labelPosition",
      "spacing",
    ],
    propsMeta: [
      {
        key: "label",
        label: "Label",
        type: "text",
        placeholder: "or",
        group: "Content",
      },
      {
        key: "orientation",
        label: "Orientation",
        type: "select",
        options: ["horizontal", "vertical"],
        group: "Appearance",
      },
      {
        key: "variant",
        label: "Style",
        type: "select",
        options: ["solid", "dashed", "dotted"],
        group: "Appearance",
      },
      {
        key: "labelPosition",
        label: "Label Pos",
        type: "select",
        options: ["left", "center", "right"],
        group: "Appearance",
      },
      { key: "color", label: "Color", type: "color", group: "Appearance" },
      {
        key: "thickness",
        label: "Thickness",
        type: "number",
        min: 1,
        max: 20,
        group: "Appearance",
      },
      {
        key: "spacing",
        label: "Spacing",
        type: "number",
        min: 0,
        max: 64,
        group: "Layout",
      },
    ],
  },
  {
    type: "Card",
    label: "Card",
    icon: "▢",
    category: "Media",
    defaultProps: { p: 16, width: 280, variant: "border" },
    editableProps: [
      "p",
      "width",
      "variant",
      "glowColor",
      "title",
      "description",
    ],
    propsMeta: [
      {
        key: "title",
        label: "Title",
        type: "text",
        placeholder: "Card title",
        group: "Content",
      },
      {
        key: "description",
        label: "Description",
        type: "text",
        placeholder: "Card description",
        group: "Content",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: ["border", "shadow", "glow"],
        group: "Appearance",
      },
      {
        key: "glowColor",
        label: "Glow Color",
        type: "select",
        options: ["", "green", "purple"],
        group: "Appearance",
      },
      {
        key: "p",
        label: "Padding",
        type: "number",
        min: 0,
        max: 64,
        group: "Layout",
      },
      {
        key: "width",
        label: "Width",
        type: "number",
        min: 0,
        max: 2000,
        group: "Layout",
      },
    ],
  },

  // ── Feedback ────────────────────────────────────────────────────────────────
  {
    type: "Toast",
    label: "Toast",
    icon: "◐",
    category: "Feedback",
    defaultProps: {
      message: "Operation successful",
      variant: "success",
      duration: 3000,
    },
    editableProps: ["message", "variant", "duration"],
    propsMeta: [
      {
        key: "message",
        label: "Message",
        type: "text",
        placeholder: "Operation successful",
        group: "Content",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: ["success", "error", "warning", "info"],
        group: "Appearance",
      },
      {
        key: "duration",
        label: "Duration (ms)",
        type: "number",
        min: 0,
        max: 10000,
        group: "Behaviour",
      },
    ],
  },
  {
    type: "Clipboard",
    label: "Clipboard",
    icon: "📋",
    category: "Feedback",
    defaultProps: { value: "Copy me!", showValue: true, successDuration: 2000 },
    editableProps: ["value", "displayValue", "showValue", "successDuration"],
    propsMeta: [
      {
        key: "value",
        label: "Copy Value",
        type: "text",
        placeholder: "Copy me!",
        group: "Content",
      },
      {
        key: "displayValue",
        label: "Display Value",
        type: "text",
        placeholder: "Same as value if empty",
        group: "Content",
      },
      {
        key: "showValue",
        label: "Show Value",
        type: "boolean",
        group: "Appearance",
      },
      {
        key: "successDuration",
        label: "Success (ms)",
        type: "number",
        min: 0,
        max: 10000,
        group: "Behaviour",
      },
    ],
  },
  {
    type: "Resizer",
    label: "Resizer",
    icon: "⤡",
    category: "Feedback",
    defaultProps: { defaultWidth: 400, minWidth: 200, direction: "horizontal" },
    editableProps: [
      "defaultWidth",
      "defaultHeight",
      "minWidth",
      "maxWidth",
      "minHeight",
      "maxHeight",
      "direction",
      "handleColor",
    ],
    propsMeta: [
      {
        key: "defaultWidth",
        label: "Default W",
        type: "number",
        min: 0,
        max: 2000,
        group: "Layout",
      },
      {
        key: "defaultHeight",
        label: "Default H",
        type: "number",
        min: 0,
        max: 2000,
        group: "Layout",
      },
      {
        key: "minWidth",
        label: "Min W",
        type: "number",
        min: 0,
        max: 2000,
        group: "Layout",
      },
      {
        key: "maxWidth",
        label: "Max W",
        type: "number",
        min: 0,
        max: 2000,
        group: "Layout",
      },
      {
        key: "minHeight",
        label: "Min H",
        type: "number",
        min: 0,
        max: 2000,
        group: "Layout",
      },
      {
        key: "maxHeight",
        label: "Max H",
        type: "number",
        min: 0,
        max: 2000,
        group: "Layout",
      },
      {
        key: "direction",
        label: "Direction",
        type: "select",
        options: ["horizontal", "vertical", "both"],
        group: "Behaviour",
      },
      {
        key: "handleColor",
        label: "Handle Color",
        type: "color",
        group: "Appearance",
      },
    ],
  },
  {
    type: "ProgressPanel",
    label: "ProgressPanel",
    icon: "▦",
    category: "Feedback",
    defaultProps: { steps: 4, current: 2 },
    editableProps: ["steps", "current"],
    propsMeta: [
      {
        key: "steps",
        label: "# Steps",
        type: "number",
        min: 1,
        max: 20,
        group: "Content",
      },
      {
        key: "current",
        label: "Active Step",
        type: "number",
        min: 0,
        max: 19,
        group: "Content",
      },
    ],
  },
  {
    type: "Spinner",
    label: "Spinner",
    icon: "◌",
    category: "Feedback",
    defaultProps: { size: "md", variant: "ring" },
    editableProps: ["size", "variant", "color", "trackColor", "label"],
    propsMeta: [
      {
        key: "label",
        label: "Label (a11y)",
        type: "text",
        placeholder: "Loading...",
        group: "Content",
      },
      {
        key: "size",
        label: "Size",
        type: "select",
        options: ["xs", "sm", "md", "lg", "xl"],
        group: "Appearance",
      },
      {
        key: "variant",
        label: "Variant",
        type: "select",
        options: ["ring", "dots", "pulse"],
        group: "Appearance",
      },
      { key: "color", label: "Color", type: "color", group: "Appearance" },
      {
        key: "trackColor",
        label: "Track Color",
        type: "color",
        group: "Appearance",
      },
    ],
  },
];

export const CATEGORY_ICONS: Record<string, string> = {
  Layout: "◇",
  Buttons: "▤",
  Inputs: "⌨",
  Data: "⊟",
  Navigation: "≡",
  Overlay: "◻",
  Media: "◒",
  Feedback: "◐",
};

export const TOKENS_CATEGORIES: Record<string, Record<string, string>> = {
  Colors: {
    Primary: "#ff6a1a",
    Background: "#020205",
    Surface: "rgba(255,255,255,0.04)",
    "Surface-2": "rgba(255,255,255,0.08)",
    Text: "#f8f0e8",
    "Text-2": "rgba(248,240,232,0.6)",
    Border: "rgba(255,106,26,0.15)",
    Success: "#22c55e",
    Error: "#dc143c",
    Warning: "#f59e0b",
  },
  Spacing: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    "2xl": "48px",
    "3xl": "64px",
    "4xl": "96px",
  },
  Typography: {
    H1: "2.5rem",
    H2: "2rem",
    H3: "1.5rem",
    H4: "1.25rem",
    Body: "1rem",
    Small: "0.875rem",
    XS: "0.75rem",
    "Weight-Bold": "700",
    "Weight-Medium": "500",
    "Weight-Regular": "400",
  },
  Radius: {
    none: "0",
    sm: "4px",
    md: "8px",
    lg: "12px",
    xl: "16px",
    "2xl": "24px",
    full: "9999px",
  },
  Shadow: {
    sm: "0 1px 2px rgba(0,0,0,0.3)",
    md: "0 4px 12px rgba(0,0,0,0.3)",
    lg: "0 8px 24px rgba(0,0,0,0.4)",
    xl: "0 12px 48px rgba(0,0,0,0.5)",
  },
};
